# Generated by Django 2.2.6 on 2019-10-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reeluser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
