# Generated by Django 2.2.6 on 2019-10-21 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20191018_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reeluser',
            old_name='age',
            new_name='age1',
        ),
    ]
