# Generated by Django 2.2.6 on 2019-10-25 10:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_remove_reeluser_age1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='email',
            field=models.EmailField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='msg',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='receipe_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='water', to='blogapp.Receipe'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='subject',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='receipe_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food', to='blogapp.Receipe'),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='category',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='prep_time',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='pub_date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='receipe_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='step',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
