# Generated by Django 2.2.6 on 2019-10-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_auto_20191025_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='reeluser',
            name='token',
            field=models.CharField(default='111', max_length=255, null=True),
        ),
    ]
