# Generated by Django 2.2.6 on 2019-10-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_reeluser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='recipe_image',
            field=models.FileField(blank=True, null=True, upload_to='assets1'),
        ),
    ]
