# Generated by Django 2.2.6 on 2019-10-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_receipe_recipe_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipe',
            options={'get_latest_by': 'pub_date'},
        ),
        migrations.AlterField(
            model_name='receipe',
            name='recipe_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterModelTable(
            name='receipe',
            table=None,
        ),
    ]
