# Generated by Django 2.2.6 on 2019-10-29 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_auto_20191029_0345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipe',
            options={},
        ),
        migrations.AlterModelTable(
            name='receipe',
            table='receipe',
        ),
    ]
