# Generated by Django 2.2.6 on 2019-10-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_auto_20191029_0353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'slider',
            },
        ),
        migrations.CreateModel(
            name='Slider_child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_caption1', models.CharField(blank=True, max_length=100, null=True)),
                ('slider_caption2', models.CharField(blank=True, max_length=100, null=True)),
                ('slider_caption3', models.CharField(blank=True, max_length=100, null=True)),
                ('slider_image', models.ManyToManyField(blank=True, to='blogapp.Slider')),
            ],
            options={
                'db_table': 'slider_child',
            },
        ),
    ]
