# Generated by Django 2.2.6 on 2019-10-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_auto_20191030_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='category',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='receipe name'),
        ),
    ]
