# Generated by Django 2.2.6 on 2019-10-31 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_auto_20191031_0616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='receipe',
            options={'ordering': ['pub_date'], 'verbose_name_plural': 'Receipe'},
        ),
        migrations.AlterModelOptions(
            name='reeluser',
            options={'verbose_name_plural': 'Reeluser'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Sliderssssssss'},
        ),
        migrations.AlterModelOptions(
            name='slider_child',
            options={'verbose_name_plural': 'Slider_child'},
        ),
        migrations.AlterModelTable(
            name='reeluser',
            table=None,
        ),
    ]
