# Generated by Django 2.2.6 on 2019-10-31 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_auto_20191031_0656'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reeluser',
            table='reeluser',
        ),
    ]
