# Generated by Django 2.2.6 on 2019-10-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_auto_20191031_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(blank=True, max_length=30, null=True)),
                ('social_url', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Social Links',
                'db_table': 'social_links',
            },
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slider'},
        ),
        migrations.AddField(
            model_name='slider',
            name='slider_caption1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='slider_caption2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='slider_caption3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Slider_child',
        ),
    ]
