# Generated by Django 2.2.6 on 2019-11-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_auto_20191101_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('subject', models.CharField(blank=True, max_length=25, null=True)),
                ('msg', models.TextField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=25, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'contact',
                'db_table': 'contact',
            },
        ),
    ]
