# Generated by Django 2.2.6 on 2019-11-04 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0018_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'contact'},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='msg',
            new_name='contact_msg',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='contact_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='contact_subject',
        ),
    ]
