# Generated by Django 2.2.6 on 2019-11-04 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0019_auto_20191104_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_image', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'footerimage',
            },
        ),
        migrations.AlterField(
            model_name='receipe',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
