# Generated by Django 2.2.6 on 2019-11-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0020_auto_20191104_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerimage',
            options={'verbose_name_plural': 'FooterImage'},
        ),
        migrations.RenameField(
            model_name='footerimage',
            old_name='footer_image',
            new_name='image',
        ),
    ]
