# Generated by Django 2.2.6 on 2019-11-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0021_auto_20191104_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=25, null=True)),
                ('numbers', models.IntegerField(blank=True, null=True)),
                ('image2', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'AboutUs',
                'db_table': 'aboutus',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=25, null=True)),
                ('text2', models.CharField(blank=True, max_length=25, null=True)),
                ('heading', models.CharField(blank=True, max_length=25, null=True)),
                ('image1', models.FileField(blank=True, null=True, upload_to='')),
                ('image2', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'feature',
                'db_table': 'feature',
            },
        ),
    ]
