# Generated by Django 2.2.6 on 2019-11-05 04:59

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0023_auto_20191105_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
            ],
            options={
                'verbose_name_plural': 'Placelocation',
                'db_table': 'place',
            },
        ),
    ]
