# Generated by Django 2.2.6 on 2019-11-05 05:20

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0024_placelocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placelocation',
            name='position',
            field=django_google_maps.fields.GeoLocationField(max_length=100),
        ),
    ]
