# Generated by Django 2.2.6 on 2019-11-05 05:26

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0025_auto_20191105_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placelocation',
            name='name',
            field=django_google_maps.fields.AddressField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='placelocation',
            name='position',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
    ]
