# Generated by Django 2.2.6 on 2019-11-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0026_auto_20191105_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placelocation',
            name='position',
        ),
        migrations.AddField(
            model_name='placelocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='placelocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='placelocation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
