# Generated by Django 2.2.6 on 2019-11-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0029_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
