# Generated by Django 2.2.6 on 2019-11-08 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0031_comments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='heading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about', to='blogapp.Feature'),
        ),
    ]
