# Generated by Django 2.2.6 on 2019-11-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0032_aboutus_heading'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'contact'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'feature'},
        ),
        migrations.AlterModelOptions(
            name='receipe',
            options={'ordering': ['pub_date'], 'verbose_name': 'Receipe'},
        ),
        migrations.AlterModelOptions(
            name='reeluser',
            options={'verbose_name': 'Reeluser'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slider'},
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
