# Generated by Django 2.2.6 on 2019-11-11 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0034_auto_20191108_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='heading2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('heading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='blogapp.Feature')),
            ],
            options={
                'verbose_name_plural': 'Newsletter',
                'db_table': 'newsletter',
            },
        ),
    ]
