# Generated by Django 2.2.6 on 2019-11-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0035_auto_20191111_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
