# Generated by Django 2.2.6 on 2019-11-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0036_details_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='heading1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='heading2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='heading3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
