# Generated by Django 2.2.6 on 2019-11-12 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0037_auto_20191112_0636'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Address',
        ),
    ]
