# Generated by Django 2.2.6 on 2019-11-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0038_auto_20191112_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
